version: 0.2

phases:

  pre_build:
    commands:
      - echo "Environment variables:"
      - echo "RUN_01_TUNING_SCRIPT=$RUN_01_TUNING_SCRIPT"
      - echo "RUN_02_TRAINING_SCRIPT=$RUN_02_TRAINING_SCRIPT"
      - echo "FIT_TEST_MODEL=$FIT_TEST_MODEL"
      - echo "MLFLOW_ARTIFACT_ROOT=$MLFLOW_ARTIFACT_ROOT"

  build:
    commands:
      - echo "Starting Docker container..."
      - docker build -t tbclassifier .
      - docker run --rm \
          -e RUN_01_TUNING_SCRIPT=$RUN_01_TUNING_SCRIPT \
          -e RUN_02_TRAINING_SCRIPT=$RUN_02_TRAINING_SCRIPT \
          -e FIT_TEST_MODEL=$FIT_TEST_MODEL \
          -e MLFLOW_ARTIFACT_ROOT=$MLFLOW_ARTIFACT_ROOT \
          tbclassifier

artifacts:
  files:
    - "**/*"
  base-directory: "."