FROM python:3.11-slim
WORKDIR /TBClassifier
COPY requirements.txt .
RUN python -m pip install --upgrade "pip==24.0" \
    && pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["python", "01_TBClassifier_training.py"]