FROM python:3.10-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libgomp1 \
    libmagic1 \
    && rm -rf /var/lib/apt/lists/*
COPY requirements-inference.txt .
RUN pip install --no-cache-dir -r requirements-inference.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "02_TBClassifier_inference:app", "--host", "0.0.0.0", "--port", "8000"]