name: TB Classifier Pipeline

permissions:
  id-token: write
  contents: read

env:
  RUN_01_TRAINING_SCRIPT:         ${{ vars.RUN_01_TRAINING_SCRIPT }}
  RUN_02_DEPLOY_SCRIPT:           ${{ vars.RUN_02_DEPLOY_SCRIPT }}
  MLFLOW_DEFAULT_ARTIFACT_ROOT:   ${{ vars.MLFLOW_DEFAULT_ARTIFACT_ROOT }}
  DEMO_VERSION:                   ${{ vars.DEMO_VERSION }}
on: 
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      reason:
        description: "Manual trigger reason"
        type: string
        default: "manual-deploy"

jobs:

  show-settings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display Pipeline Settings
        run: |
          echo "=========================================="
          echo "PIPELINE SETTINGS"
          echo "=========================================="
          echo "Trigger:                            ${{ github.event_name }}"
          echo "Reason:                             ${{ github.event.inputs.reason || 'N/A' }}"
          echo "RUN_01_TRAINING_SCRIPT:             ${{ vars.RUN_01_TRAINING_SCRIPT }}"
          echo "RUN_02_DEPLOY_SCRIPT:               ${{ vars.RUN_02_DEPLOY_SCRIPT }}"
          echo "MLFLOW_DEFAULT_ARTIFACT_ROOT:       ${{ vars.MLFLOW_DEFAULT_ARTIFACT_ROOT }}"
          echo "DEMO_VERSION:                       ${{ vars.DEMO_VERSION }}"
          echo "=========================================="

  train:
    needs: [show-settings]
    runs-on: ubuntu-latest
    if: vars.RUN_01_TRAINING_SCRIPT == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Build & Run Docker
        run: |
          echo "Build & Run Docker"
          docker build -f dockerfile.train -t tbclassifier .
          docker run --rm \
            -e DEMO_VERSION=$DEMO_VERSION \
            -e MLFLOW_DEFAULT_ARTIFACT_ROOT=$MLFLOW_DEFAULT_ARTIFACT_ROOT \
            tbclassifier

  deploy:
    needs: [show-settings]
    runs-on: ubuntu-latest
    if: vars.RUN_02_DEPLOY_SCRIPT == 'true'

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-1
          role-to-assume: ${{ secrets.AWS_ROLE }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password \
          | docker login --username AWS \
          --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build inference image
        run: |
          docker build -f dockerfile.inference -t tb-inference .

      - name: Tag image
        run: |
          docker tag tb-inference:latest \
          ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-1.amazonaws.com/tb-inference:latest

      - name: Push image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.ap-southeast-1.amazonaws.com/tb-inference:latest          
      
      - name: Deploy ECS service
        run: |
          aws ecs update-service \
            --cluster tb-cluster \
            --service tb-service \
            --force-new-deployment